import sqlite3

# Database file path
DB_PATH = "nba_players.db"

def create_database():
    """Create the database and players table if they don't exist"""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='players'")
    table_exists = cursor.fetchone() is not None
    if not table_exists:
        cursor.execute('''
            CREATE TABLE players (
                id INTEGER PRIMARY KEY,
                name TEXT NOT NULL,
                all_star_count INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')
    else:
        cursor.execute("PRAGMA table_info(players)")
        columns = [column[1] for column in cursor.fetchall()]
        if 'all_star_count' not in columns:
            cursor.execute("ALTER TABLE players ADD COLUMN all_star_count INTEGER")
            print("✅ Added all_star_count column to existing table")
    conn.commit()
    conn.close()

def save_players_to_db(player_pool):
    """Save players to the database"""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("DELETE FROM players")
    for player in player_pool:
        cursor.execute("INSERT INTO players (id, name, all_star_count) VALUES (?, ?, ?)",
                      (player["id"], player["name"], player["all_star_count"]))
    conn.commit()
    conn.close()
    print(f"Saved {len(player_pool)} All-Star players to database")

def create_manual_all_star_list():
    print("📝 Using complete All-Star list from Basketball Reference...")

    # Pulled from Basketball Reference HTML File
    all_stars = [
        {'name': 'LeBron James', 'all_star_count': 21},
        {'name': 'Kareem Abdul-Jabbar', 'all_star_count': 19},
        {'name': 'Kobe Bryant', 'all_star_count': 18},
        {'name': 'Julius Erving', 'all_star_count': 16},
        {'name': 'Tim Duncan', 'all_star_count': 15},
        {'name': 'Kevin Durant', 'all_star_count': 15},
        {'name': 'Kevin Garnett', 'all_star_count': 15},
        {'name': 'Shaquille O\'Neal', 'all_star_count': 15},
        {'name': 'Michael Jordan', 'all_star_count': 14},
        {'name': 'Karl Malone', 'all_star_count': 14},
        {'name': 'Dirk Nowitzki', 'all_star_count': 14},
        {'name': 'Jerry West', 'all_star_count': 14},
        {'name': 'Wilt Chamberlain', 'all_star_count': 13},
        {'name': 'Bob Cousy', 'all_star_count': 13},
        {'name': 'John Havlicek', 'all_star_count': 13},
        {'name': 'Moses Malone', 'all_star_count': 13},
        {'name': 'Dwyane Wade', 'all_star_count': 13},
        {'name': 'Rick Barry', 'all_star_count': 12},
        {'name': 'Larry Bird', 'all_star_count': 12},
        {'name': 'George Gervin', 'all_star_count': 12},
        {'name': 'Elvin Hayes', 'all_star_count': 12},
        {'name': 'Magic Johnson', 'all_star_count': 12},
        {'name': 'Hakeem Olajuwon', 'all_star_count': 12},
        {'name': 'Chris Paul', 'all_star_count': 12},
        {'name': 'Oscar Robertson', 'all_star_count': 12},
        {'name': 'Bill Russell', 'all_star_count': 12},
        {'name': 'Dolph Schayes', 'all_star_count': 12},
        {'name': 'Isiah Thomas', 'all_star_count': 12},
        {'name': 'Charles Barkley', 'all_star_count': 11},
        {'name': 'Elgin Baylor', 'all_star_count': 11},
        {'name': 'Chris Bosh', 'all_star_count': 11},
        {'name': 'Stephen Curry', 'all_star_count': 11},
        {'name': 'Patrick Ewing', 'all_star_count': 11},
        {'name': 'Artis Gilmore', 'all_star_count': 11},
        {'name': 'James Harden', 'all_star_count': 11},
        {'name': 'Allen Iverson', 'all_star_count': 11},
        {'name': 'Bob Pettit', 'all_star_count': 11},
        {'name': 'Ray Allen', 'all_star_count': 10},
        {'name': 'Carmelo Anthony', 'all_star_count': 10},
        {'name': 'Paul Arizin', 'all_star_count': 10},
        {'name': 'Anthony Davis', 'all_star_count': 10},
        {'name': 'Clyde Drexler', 'all_star_count': 10},
        {'name': 'Hal Greer', 'all_star_count': 10},
        {'name': 'Jason Kidd', 'all_star_count': 10},
        {'name': 'Paul Pierce', 'all_star_count': 10},
        {'name': 'David Robinson', 'all_star_count': 10},
        {'name': 'John Stockton', 'all_star_count': 10},
        {'name': 'Giannis Antetokounmpo', 'all_star_count': 9},
        {'name': 'Paul George', 'all_star_count': 9},
        {'name': 'Kyrie Irving', 'all_star_count': 9},
        {'name': 'Damian Lillard', 'all_star_count': 9},
        {'name': 'Robert Parish', 'all_star_count': 9},
        {'name': 'Gary Payton', 'all_star_count': 9},
        {'name': 'Russell Westbrook', 'all_star_count': 9},
        {'name': 'Lenny Wilkens', 'all_star_count': 9},
        {'name': 'Dominique Wilkins', 'all_star_count': 9},
        {'name': 'Vince Carter', 'all_star_count': 8},
        {'name': 'Dave Cowens', 'all_star_count': 8},
        {'name': 'Dave DeBusschere', 'all_star_count': 8},
        {'name': 'Alex English', 'all_star_count': 8},
        {'name': 'Larry Foust', 'all_star_count': 8},
        {'name': 'Dwight Howard', 'all_star_count': 8},
        {'name': 'Bob Lanier', 'all_star_count': 8},
        {'name': 'Yao Ming', 'all_star_count': 8},
        {'name': 'Dikembe Mutombo', 'all_star_count': 8},
        {'name': 'Steve Nash', 'all_star_count': 8},
        {'name': 'Bill Sharman', 'all_star_count': 8},
        {'name': 'LaMarcus Aldridge', 'all_star_count': 7},
        {'name': 'Dave Bing', 'all_star_count': 7},
        {'name': 'Louie Dampier', 'all_star_count': 7},
        {'name': 'Mel Daniels', 'all_star_count': 7},
        {'name': 'Joel Embiid', 'all_star_count': 7},
        {'name': 'Walt Frazier', 'all_star_count': 7},
        {'name': 'Harry Gallatin', 'all_star_count': 7},
        {'name': 'Grant Hill', 'all_star_count': 7},
        {'name': 'Dan Issel', 'all_star_count': 7},
        {'name': 'Joe Johnson', 'all_star_count': 7},
        {'name': 'Nikola Jokić', 'all_star_count': 7},
        {'name': 'Jerry Lucas', 'all_star_count': 7},
        {'name': 'Ed Macauley', 'all_star_count': 7},
        {'name': 'Slater Martin', 'all_star_count': 7},
        {'name': 'Tracy McGrady', 'all_star_count': 7},
        {'name': 'Dick McGuire', 'all_star_count': 7},
        {'name': 'Kevin McHale', 'all_star_count': 7},
        {'name': 'Alonzo Mourning', 'all_star_count': 7},
        {'name': 'Scottie Pippen', 'all_star_count': 7},
        {'name': 'Willis Reed', 'all_star_count': 7},
        {'name': 'Jack Sikma', 'all_star_count': 7},
        {'name': 'Nate Thurmond', 'all_star_count': 7},
        {'name': 'Chet Walker', 'all_star_count': 7},
        {'name': 'Jo Jo White', 'all_star_count': 7},
        {'name': 'James Worthy', 'all_star_count': 7},
        {'name': 'Tiny Archibald', 'all_star_count': 6},
        {'name': 'Jimmy Butler', 'all_star_count': 6},
        {'name': 'Larry Costello', 'all_star_count': 6},
        {'name': 'Adrian Dantley', 'all_star_count': 6},
        {'name': 'Walter Davis', 'all_star_count': 6},
        {'name': 'DeMar DeRozan', 'all_star_count': 6},
        {'name': 'Joe Dumars', 'all_star_count': 6},
        {'name': 'Pau Gasol', 'all_star_count': 6},
        {'name': 'Blake Griffin', 'all_star_count': 6},
        {'name': 'Richie Guerin', 'all_star_count': 6},
        {'name': 'Cliff Hagan', 'all_star_count': 6},
        {'name': 'Connie Hawkins', 'all_star_count': 6},
        {'name': 'Tom Heinsohn', 'all_star_count': 6},
        {'name': 'Bailey Howell', 'all_star_count': 6},
        {'name': 'Lou Hudson', 'all_star_count': 6},
        {'name': 'Neil Johnston', 'all_star_count': 6},
        {'name': 'Jimmy Jones', 'all_star_count': 6},
        {'name': 'Shawn Kemp', 'all_star_count': 6},
        {'name': 'Kawhi Leonard', 'all_star_count': 6},
        {'name': 'Kyle Lowry', 'all_star_count': 6},
        {'name': 'George McGinnis', 'all_star_count': 6},
        {'name': 'Vern Mikkelsen', 'all_star_count': 6},
        {'name': 'Donovan Mitchell', 'all_star_count': 6},
        {'name': 'Jermaine O\'Neal', 'all_star_count': 6},
        {'name': 'Tony Parker', 'all_star_count': 6},
        {'name': 'Mitch Richmond', 'all_star_count': 6},
        {'name': 'Amar\'e Stoudemire', 'all_star_count': 6},
        {'name': 'Jayson Tatum', 'all_star_count': 6},
        {'name': 'Jack Twyman', 'all_star_count': 6},
        {'name': 'George Yardley', 'all_star_count': 6},
        {'name': 'Zelmo Beaty', 'all_star_count': 5},
        {'name': 'Chauncey Billups', 'all_star_count': 5},
        {'name': 'Carl Braun', 'all_star_count': 5},
        {'name': 'Mack Calvin', 'all_star_count': 5},
        {'name': 'Billy Cunningham', 'all_star_count': 5},
        {'name': 'Brad Daugherty', 'all_star_count': 5},
        {'name': 'Luka Dončić', 'all_star_count': 5},
        {'name': 'Wayne Embry', 'all_star_count': 5},
        {'name': 'Donnie Freeman', 'all_star_count': 5},
        {'name': 'Tom Gola', 'all_star_count': 5},
        {'name': 'Gail Goodrich', 'all_star_count': 5},
        {'name': 'Tim Hardaway', 'all_star_count': 5},
        {'name': 'Spencer Haywood', 'all_star_count': 5},
        {'name': 'Al Horford', 'all_star_count': 5},
        {'name': 'Dennis Johnson', 'all_star_count': 5},
        {'name': 'Gus Johnson', 'all_star_count': 5},
        {'name': 'Marques Johnson', 'all_star_count': 5},
        {'name': 'Bobby Jones', 'all_star_count': 5},
        {'name': 'Sam Jones', 'all_star_count': 5},
        {'name': 'Larry Kenon', 'all_star_count': 5},
        {'name': 'Rudy LaRusso', 'all_star_count': 5},
        {'name': 'Kevin Love', 'all_star_count': 5},
        {'name': 'Maurice Lucas', 'all_star_count': 5},
        {'name': 'Pete Maravich', 'all_star_count': 5},
        {'name': 'Bob McAdoo', 'all_star_count': 5},
        {'name': 'Reggie Miller', 'all_star_count': 5},
        {'name': 'Sidney Moncrief', 'all_star_count': 5},
        {'name': 'Chris Mullin', 'all_star_count': 5},
        {'name': 'Don Ohl', 'all_star_count': 5},
        {'name': 'Andy Phillip', 'all_star_count': 5},
        {'name': 'Charlie Scott', 'all_star_count': 5},
        {'name': 'Gene Shue', 'all_star_count': 5},
        {'name': 'Ralph Simpson', 'all_star_count': 5},
        {'name': 'David Thompson', 'all_star_count': 5},
        {'name': 'Klay Thompson', 'all_star_count': 5},
        {'name': 'Rudy Tomjanovich', 'all_star_count': 5},
        {'name': 'Karl-Anthony Towns', 'all_star_count': 5},
        {'name': 'Wes Unseld', 'all_star_count': 5},
        {'name': 'John Wall', 'all_star_count': 5},
        {'name': 'Bobby Wanzer', 'all_star_count': 5},
        {'name': 'Chris Webber', 'all_star_count': 5},
        {'name': 'Paul Westphal', 'all_star_count': 5},
        {'name': 'Vin Baker', 'all_star_count': 4},
        {'name': 'Walt Bellamy', 'all_star_count': 4},
        {'name': 'Otis Birdsong', 'all_star_count': 4},
        {'name': 'Rolando Blackman', 'all_star_count': 4},
        {'name': 'Devin Booker', 'all_star_count': 4},
        {'name': 'Ron Boone', 'all_star_count': 4},
        {'name': 'Jaylen Brown', 'all_star_count': 4},
        {'name': 'Roger Brown', 'all_star_count': 4},
        {'name': 'Joe Caldwell', 'all_star_count': 4},
        {'name': 'Tom Chambers', 'all_star_count': 4},
        {'name': 'Maurice Cheeks', 'all_star_count': 4},
        {'name': 'Doug Collins', 'all_star_count': 4},
        {'name': 'DeMarcus Cousins', 'all_star_count': 4},
        {'name': 'Bob Dandridge', 'all_star_count': 4},
        {'name': 'Bob Davies', 'all_star_count': 4},
        {'name': 'Dick Garmaker', 'all_star_count': 4},
        {'name': 'Draymond Green', 'all_star_count': 4},
        {'name': 'Johnny Green', 'all_star_count': 4},
        {'name': 'Anfernee Hardaway', 'all_star_count': 4},
        {'name': 'Mel Hutchins', 'all_star_count': 4},
        {'name': 'Warren Jabali', 'all_star_count': 4},
        {'name': 'Larry Jones', 'all_star_count': 4},
        {'name': 'Bernard King', 'all_star_count': 4},
        {'name': 'Bill Laimbeer', 'all_star_count': 4},
        {'name': 'Clyde Lovellette', 'all_star_count': 4},
        {'name': 'Shawn Marion', 'all_star_count': 4},
        {'name': 'George Mikan', 'all_star_count': 4},
        {'name': 'Paul Millsap', 'all_star_count': 4},
        {'name': 'Earl Monroe', 'all_star_count': 4},
        {'name': 'Willie Naulls', 'all_star_count': 4},
        {'name': 'Bob Netolicky', 'all_star_count': 4},
        {'name': 'Billy Paultz', 'all_star_count': 4},
        {'name': 'Jim Pollard', 'all_star_count': 4},
        {'name': 'Mark Price', 'all_star_count': 4},
        {'name': 'Michael Ray Richardson', 'all_star_count': 4},
        {'name': 'Arnie Risen', 'all_star_count': 4},
        {'name': 'Red Robbins', 'all_star_count': 4},
        {'name': 'Alvin Robertson', 'all_star_count': 4},
        {'name': 'Guy Rodgers', 'all_star_count': 4},
        {'name': 'Rajon Rondo', 'all_star_count': 4},
        {'name': 'Ralph Sampson', 'all_star_count': 4},
        {'name': 'Latrell Sprewell', 'all_star_count': 4},
        {'name': 'Kemba Walker', 'all_star_count': 4},
        {'name': 'Ben Wallace', 'all_star_count': 4},
        {'name': 'Rasheed Wallace', 'all_star_count': 4},
        {'name': 'Sidney Wicks', 'all_star_count': 4},
        {'name': 'Trae Young', 'all_star_count': 4},
        {'name': 'Bam Adebayo', 'all_star_count': 3},
        {'name': 'Mark Aguirre', 'all_star_count': 3},
        {'name': 'Gilbert Arenas', 'all_star_count': 3},
        {'name': 'Bradley Beal', 'all_star_count': 3},
        {'name': 'John Beasley', 'all_star_count': 3},
        {'name': 'Bill Bridges', 'all_star_count': 3},
        {'name': 'Larry Brown', 'all_star_count': 3},
        {'name': 'Darel Carrier', 'all_star_count': 3},
        {'name': 'Phil Chenier', 'all_star_count': 3},
        {'name': 'Glen Combs', 'all_star_count': 3},
        {'name': 'Terry Dischinger', 'all_star_count': 3},
        {'name': 'Anthony Edwards', 'all_star_count': 3},
        {'name': 'Steve Francis', 'all_star_count': 3},
        {'name': 'Marc Gasol', 'all_star_count': 3},
        {'name': 'Shai Gilgeous-Alexander', 'all_star_count': 3},
        {'name': 'Rudy Gobert', 'all_star_count': 3},
        {'name': 'Richard Hamilton', 'all_star_count': 3},
        {'name': 'Kevin Johnson', 'all_star_count': 3},
        {'name': 'Stew Johnson', 'all_star_count': 3},
        {'name': 'Eddie Jones', 'all_star_count': 3},
        {'name': 'Steve Jones', 'all_star_count': 3},
        {'name': 'Bob Kauffman', 'all_star_count': 3},
        {'name': 'Red Kerr', 'all_star_count': 3},
        {'name': 'Billy Knight', 'all_star_count': 3},
        {'name': 'Freddie Lewis', 'all_star_count': 3},
        {'name': 'Bob Love', 'all_star_count': 3},
        {'name': 'Dan Majerle', 'all_star_count': 3},
        {'name': 'Bill Melchionni', 'all_star_count': 3},
        {'name': 'Khris Middleton', 'all_star_count': 3},
        {'name': 'Doug Moe', 'all_star_count': 3},
        {'name': 'Jeff Mullins', 'all_star_count': 3},
        {'name': 'Larry Nance', 'all_star_count': 3},
        {'name': 'Julius Randle', 'all_star_count': 3},
        {'name': 'Glen Rice', 'all_star_count': 3},
        {'name': 'Derrick Rose', 'all_star_count': 3},
        {'name': 'Dan Roundfield', 'all_star_count': 3},
        {'name': 'Brandon Roy', 'all_star_count': 3},
        {'name': 'Domantas Sabonis', 'all_star_count': 3},
        {'name': 'Detlef Schrempf', 'all_star_count': 3},
        {'name': 'Paul Seymour', 'all_star_count': 3},
        {'name': 'Pascal Siakam', 'all_star_count': 3},
        {'name': 'Ben Simmons', 'all_star_count': 3},
        {'name': 'Peja Stojaković', 'all_star_count': 3},
        {'name': 'Maurice Stokes', 'all_star_count': 3},
        {'name': 'George Thompson', 'all_star_count': 3},
        {'name': 'Dick Van Arsdale', 'all_star_count': 3},
        {'name': 'Tom Van Arsdale', 'all_star_count': 3},
        {'name': 'Norm Van Lier', 'all_star_count': 3},
        {'name': 'Antoine Walker', 'all_star_count': 3},
        {'name': 'Jamaal Wilkes', 'all_star_count': 3},
        {'name': 'Buck Williams', 'all_star_count': 3},
        {'name': 'Deron Williams', 'all_star_count': 3},
        {'name': 'Willie Wise', 'all_star_count': 3},
        {'name': 'Marvin Barnes', 'all_star_count': 2},
        {'name': 'Leo Barnhorst', 'all_star_count': 2},
        {'name': 'Byron Beck', 'all_star_count': 2},
        {'name': 'Art Becker', 'all_star_count': 2},
        {'name': 'Carlos Boozer', 'all_star_count': 2},
        {'name': 'Elton Brand', 'all_star_count': 2},
        {'name': 'Terrell Brandon', 'all_star_count': 2},
        {'name': 'Frankie Brian', 'all_star_count': 2},
        {'name': 'John Brisker', 'all_star_count': 2},
        {'name': 'Jalen Brunson', 'all_star_count': 2},
        {'name': 'Don Buse', 'all_star_count': 2},
        {'name': 'Caron Butler', 'all_star_count': 2},
        {'name': 'Archie Clark', 'all_star_count': 2},
        {'name': 'Terry Cummings', 'all_star_count': 2},
        {'name': 'Baron Davis', 'all_star_count': 2},
        {'name': 'Warren Davis', 'all_star_count': 2},
        {'name': 'Luol Deng', 'all_star_count': 2},
        {'name': 'John Drew', 'all_star_count': 2},
        {'name': 'Andre Drummond', 'all_star_count': 2},
        {'name': 'Kevin Duckworth', 'all_star_count': 2},
        {'name': 'Walter Dukes', 'all_star_count': 2},
        {'name': 'Dike Eddleman', 'all_star_count': 2},
        {'name': 'Sean Elliott', 'all_star_count': 2},
        {'name': 'Michael Finley', 'all_star_count': 2},
        {'name': 'Joe Fulks', 'all_star_count': 2},
        {'name': 'Darius Garland', 'all_star_count': 2},
        {'name': 'Jack George', 'all_star_count': 2},
        {'name': 'Manu Ginóbili', 'all_star_count': 2},
        {'name': 'Tyrese Haliburton', 'all_star_count': 2},
        {'name': 'Roy Hibbert', 'all_star_count': 2},
        {'name': 'Jrue Holiday', 'all_star_count': 2},
        {'name': 'Allan Houston', 'all_star_count': 2},
        {'name': 'Hot Rod Hundley', 'all_star_count': 2},
        {'name': 'Les Hunter', 'all_star_count': 2},
        {'name': 'Zydrunas Ilgauskas', 'all_star_count': 2},
        {'name': 'Jaren Jackson Jr.', 'all_star_count': 2},
        {'name': 'Antawn Jamison', 'all_star_count': 2},
        {'name': 'Eddie Johnson', 'all_star_count': 2},
        {'name': 'John Johnson', 'all_star_count': 2},
        {'name': 'Larry Johnson', 'all_star_count': 2},
        {'name': 'Rich Jones', 'all_star_count': 2},
        {'name': 'Don Kojis', 'all_star_count': 2},
        {'name': 'Wendell Ladner', 'all_star_count': 2},
        {'name': 'Zach LaVine', 'all_star_count': 2},
        {'name': 'David Lee', 'all_star_count': 2},
        {'name': 'Fat Lever', 'all_star_count': 2},
        {'name': 'Mike Lewis', 'all_star_count': 2},
        {'name': 'Rashard Lewis', 'all_star_count': 2},
        {'name': 'Jeff Malone', 'all_star_count': 2},
        {'name': 'Danny Manning', 'all_star_count': 2},
        {'name': 'Stephon Marbury', 'all_star_count': 2},
        {'name': 'Jack Marin', 'all_star_count': 2},
        {'name': 'Brad Miller', 'all_star_count': 2},
        {'name': 'Ja Morant', 'all_star_count': 2},
        {'name': 'Swen Nater', 'all_star_count': 2},
        {'name': 'Norm Nixon', 'all_star_count': 2},
        {'name': 'Joakim Noah', 'all_star_count': 2},
        {'name': 'Victor Oladipo', 'all_star_count': 2},
        {'name': 'Jim Paxson', 'all_star_count': 2},
        {'name': 'Geoff Petrie', 'all_star_count': 2},
        {'name': 'Terry Porter', 'all_star_count': 2},
        {'name': 'Cincy Powell', 'all_star_count': 2},
        {'name': 'Zach Randolph', 'all_star_count': 2},
        {'name': 'Glenn Robinson', 'all_star_count': 2},
        {'name': 'Truck Robinson', 'all_star_count': 2},
        {'name': 'Red Rocha', 'all_star_count': 2},
        {'name': 'Dennis Rodman', 'all_star_count': 2},
        {'name': 'Jeff Ruland', 'all_star_count': 2},
        {'name': 'Fred Scolari', 'all_star_count': 2},
        {'name': 'Kenny Sears', 'all_star_count': 2},
        {'name': 'Frank Selvy', 'all_star_count': 2},
        {'name': 'James Silas', 'all_star_count': 2},
        {'name': 'Paul Silas', 'all_star_count': 2},
        {'name': 'Jerry Sloan', 'all_star_count': 2},
        {'name': 'Phil Smith', 'all_star_count': 2},
        {'name': 'Randy Smith', 'all_star_count': 2},
        {'name': 'Jerry Stackhouse', 'all_star_count': 2},
        {'name': 'Levern Tart', 'all_star_count': 2},
        {'name': 'Brian Taylor', 'all_star_count': 2},
        {'name': 'Reggie Theus', 'all_star_count': 2},
        {'name': 'Isaiah Thomas', 'all_star_count': 2},
        {'name': 'Andrew Toney', 'all_star_count': 2},
        {'name': 'Kelly Tripucka', 'all_star_count': 2},
        {'name': 'Kiki Vandeweghe', 'all_star_count': 2},
        {'name': 'Bob Verga', 'all_star_count': 2},
        {'name': 'Nikola Vučević', 'all_star_count': 2},
        {'name': 'Jimmy Walker', 'all_star_count': 2},
        {'name': 'Bill Walton', 'all_star_count': 2},
        {'name': 'Scott Wedman', 'all_star_count': 2},
        {'name': 'David West', 'all_star_count': 2},
        {'name': 'Charlie Williams', 'all_star_count': 2},
        {'name': 'Chuck Williams', 'all_star_count': 2},
        {'name': 'Gus Williams', 'all_star_count': 2},
        {'name': 'Zion Williamson', 'all_star_count': 2},
        {'name': 'Brian Winters', 'all_star_count': 2},
        {'name': 'Shareef Abdur-Rahim', 'all_star_count': 1},
        {'name': 'Alvan Adams', 'all_star_count': 1},
        {'name': 'Michael Adams', 'all_star_count': 1},
        {'name': 'Danny Ainge', 'all_star_count': 1},
        {'name': 'Jarrett Allen', 'all_star_count': 1},
        {'name': 'Kenny Anderson', 'all_star_count': 1},
        {'name': 'B.J. Armstrong', 'all_star_count': 1},
        {'name': 'LaMelo Ball', 'all_star_count': 1},
        {'name': 'Paolo Banchero', 'all_star_count': 1},
        {'name': 'Don Barksdale', 'all_star_count': 1},
        {'name': 'Scottie Barnes', 'all_star_count': 1},
        {'name': 'Dick Barnett', 'all_star_count': 1},
        {'name': 'Dana Barros', 'all_star_count': 1},
        {'name': 'Butch Beard', 'all_star_count': 1},
        {'name': 'Ralph Beard', 'all_star_count': 1},
        {'name': 'Mookie Blaylock', 'all_star_count': 1},
        {'name': 'John Block', 'all_star_count': 1},
        {'name': 'Bob Boozer', 'all_star_count': 1},
        {'name': 'Vince Boryla', 'all_star_count': 1},
        {'name': 'Bill Bradley', 'all_star_count': 1},
        {'name': 'Fred Brown', 'all_star_count': 1},
        {'name': 'Roger Brown', 'all_star_count': 1},
        {'name': 'Larry Bunce', 'all_star_count': 1},
        {'name': 'Andrew Bynum', 'all_star_count': 1},
        {'name': 'Austin Carr', 'all_star_count': 1},
        {'name': 'Joe Barry Carroll', 'all_star_count': 1},
        {'name': 'George Carter', 'all_star_count': 1},
        {'name': 'Bill Cartwright', 'all_star_count': 1},
        {'name': 'Sam Cassell', 'all_star_count': 1},
        {'name': 'Cedric Ceballos', 'all_star_count': 1},
        {'name': 'Tyson Chandler', 'all_star_count': 1},
        {'name': 'Len Chappell', 'all_star_count': 1},
        {'name': 'Nat Clifton', 'all_star_count': 1},
        {'name': 'Derrick Coleman', 'all_star_count': 1},
        {'name': 'Jack Coleman', 'all_star_count': 1},
        {'name': 'Mike Conley', 'all_star_count': 1},
        {'name': 'Cade Cunningham', 'all_star_count': 1},
        {'name': 'Antonio Davis', 'all_star_count': 1},
        {'name': 'Dale Davis', 'all_star_count': 1},
        {'name': 'Vlade Divac', 'all_star_count': 1},
        {'name': 'James Donaldson', 'all_star_count': 1},
        {'name': 'Goran Dragić', 'all_star_count': 1},
        {'name': 'Jim Eakins', 'all_star_count': 1},
        {'name': 'Mark Eaton', 'all_star_count': 1},
        {'name': 'Dale Ellis', 'all_star_count': 1},
        {'name': 'Ray Felix', 'all_star_count': 1},
        {'name': 'Sleepy Floyd', 'all_star_count': 1},
        {'name': 'Jimmy Foster', 'all_star_count': 1},
        {'name': 'De\'Aaron Fox', 'all_star_count': 1},
        {'name': 'World B. Free', 'all_star_count': 1},
        {'name': 'Bill Gabor', 'all_star_count': 1},
        {'name': 'Chris Gatling', 'all_star_count': 1},
        {'name': 'Gus Gerard', 'all_star_count': 1},
        {'name': 'Gerald Govan', 'all_star_count': 1},
        {'name': 'Danny Granger', 'all_star_count': 1},
        {'name': 'Horace Grant', 'all_star_count': 1},
        {'name': 'A.C. Green', 'all_star_count': 1},
        {'name': 'Mike Green', 'all_star_count': 1},
        {'name': 'Rickey Green', 'all_star_count': 1},
        {'name': 'Alex Groza', 'all_star_count': 1},
        {'name': 'Tom Gugliotta', 'all_star_count': 1},
        {'name': 'Devin Harris', 'all_star_count': 1},
        {'name': 'Bob Harrison', 'all_star_count': 1},
        {'name': 'Hersey Hawkins', 'all_star_count': 1},
        {'name': 'Gordon Hayward', 'all_star_count': 1},
        {'name': 'Walt Hazzard', 'all_star_count': 1},
        {'name': 'Tyler Herro', 'all_star_count': 1},
        {'name': 'Art Heyman', 'all_star_count': 1},
        {'name': 'Wayne Hightower', 'all_star_count': 1},
        {'name': 'Tyrone Hill', 'all_star_count': 1},
        {'name': 'Lionel Hollins', 'all_star_count': 1},
        {'name': 'Jeff Hornacek', 'all_star_count': 1},
        {'name': 'Josh Howard', 'all_star_count': 1},
        {'name': 'Juwan Howard', 'all_star_count': 1},
        {'name': 'Andre Iguodala', 'all_star_count': 1},
        {'name': 'Darrall Imhoff', 'all_star_count': 1},
        {'name': 'Brandon Ingram', 'all_star_count': 1},
        {'name': 'Luke Jackson', 'all_star_count': 1},
        {'name': 'Mark Jackson', 'all_star_count': 1},
        {'name': 'Merv Jackson', 'all_star_count': 1},
        {'name': 'Tony Jackson', 'all_star_count': 1},
        {'name': 'Neil Johnson', 'all_star_count': 1},
        {'name': 'Steve Johnson', 'all_star_count': 1},
        {'name': 'Caldwell Jones', 'all_star_count': 1},
        {'name': 'Wil Jones', 'all_star_count': 1},
        {'name': 'DeAndre Jordan', 'all_star_count': 1},
        {'name': 'Chris Kaman', 'all_star_count': 1},
        {'name': 'Julius Keye', 'all_star_count': 1},
        {'name': 'Jim King', 'all_star_count': 1},
        {'name': 'Andrei Kirilenko', 'all_star_count': 1},
        {'name': 'Kyle Korver', 'all_star_count': 1},
        {'name': 'Sam Lacey', 'all_star_count': 1},
        {'name': 'Christian Laettner', 'all_star_count': 1},
        {'name': 'Clyde Lee', 'all_star_count': 1},
        {'name': 'Reggie Lewis', 'all_star_count': 1},
        {'name': 'Goose Ligon', 'all_star_count': 1},
        {'name': 'Brook Lopez', 'all_star_count': 1},
        {'name': 'Jamaal Magloire', 'all_star_count': 1},
        {'name': 'Randy Mahaffey', 'all_star_count': 1},
        {'name': 'Lauri Markkanen', 'all_star_count': 1},
        {'name': 'Kenyon Martin', 'all_star_count': 1},
        {'name': 'Jamal Mashburn', 'all_star_count': 1},
        {'name': 'Anthony Mason', 'all_star_count': 1},
        {'name': 'Tyrese Maxey', 'all_star_count': 1},
        {'name': 'Ted McClain', 'all_star_count': 1},
        {'name': 'Xavier McDaniel', 'all_star_count': 1},
        {'name': 'Jim McDaniels', 'all_star_count': 1},
        {'name': 'Antonio McDyess', 'all_star_count': 1},
        {'name': 'Jon McGlocklin', 'all_star_count': 1},
        {'name': 'Dewitt Menyard', 'all_star_count': 1},
        {'name': 'Tom Meschery', 'all_star_count': 1},
        {'name': 'Eddie Miles', 'all_star_count': 1},
        {'name': 'Mike Mitchell', 'all_star_count': 1},
        {'name': 'Steve Mix', 'all_star_count': 1},
        {'name': 'Evan Mobley', 'all_star_count': 1},
        {'name': 'Jack Molinas', 'all_star_count': 1},
        {'name': 'Gene Moore', 'all_star_count': 1},
        {'name': 'Calvin Murphy', 'all_star_count': 1},
        {'name': 'Dejounte Murray', 'all_star_count': 1},
        {'name': 'Calvin Natt', 'all_star_count': 1},
        {'name': 'Jameer Nelson', 'all_star_count': 1},
        {'name': 'Chuck Noble', 'all_star_count': 1},
        {'name': 'Charles Oakley', 'all_star_count': 1},
        {'name': 'Mehmet Okur', 'all_star_count': 1},
        {'name': 'Ricky Pierce', 'all_star_count': 1},
        {'name': 'Kristaps Porziņģis', 'all_star_count': 1},
        {'name': 'Jim Price', 'all_star_count': 1},
        {'name': 'Theo Ratliff', 'all_star_count': 1},
        {'name': 'Michael Redd', 'all_star_count': 1},
        {'name': 'Richie Regan', 'all_star_count': 1},
        {'name': 'Doc Rivers', 'all_star_count': 1},
        {'name': 'Clifford Robinson', 'all_star_count': 1},
        {'name': 'Flynn Robinson', 'all_star_count': 1},
        {'name': 'Curtis Rowe', 'all_star_count': 1},
        {'name': 'Bob Rule', 'all_star_count': 1},
        {'name': 'Campy Russell', 'all_star_count': 1},
        {'name': 'Cazzie Russell', 'all_star_count': 1},
        {'name': 'D\'Angelo Russell', 'all_star_count': 1},
        {'name': 'Woody Sauldsberry', 'all_star_count': 1},
        {'name': 'Fred Schaus', 'all_star_count': 1},
        {'name': 'Alperen Şengün', 'all_star_count': 1},
        {'name': 'Lee Shaffer', 'all_star_count': 1},
        {'name': 'Lonnie Shelton', 'all_star_count': 1},
        {'name': 'Walt Simon', 'all_star_count': 1},
        {'name': 'Adrian Smith', 'all_star_count': 1},
        {'name': 'Steve Smith', 'all_star_count': 1},
        {'name': 'Rik Smits', 'all_star_count': 1},
        {'name': 'Willie Somerset', 'all_star_count': 1},
        {'name': 'John Starks', 'all_star_count': 1},
        {'name': 'Don Sunderlage', 'all_star_count': 1},
        {'name': 'Wally Szczerbiak', 'all_star_count': 1},
        {'name': 'Jeff Teague', 'all_star_count': 1},
        {'name': 'Claude Terry', 'all_star_count': 1},
        {'name': 'Skip Thoren', 'all_star_count': 1},
        {'name': 'Otis Thorpe', 'all_star_count': 1},
        {'name': 'Monte Towe', 'all_star_count': 1},
        {'name': 'Dave Twardzik', 'all_star_count': 1},
        {'name': 'Nick Van Exel', 'all_star_count': 1},
        {'name': 'Fred VanVleet', 'all_star_count': 1},
        {'name': 'Chico Vaughn', 'all_star_count': 1},
        {'name': 'Gerald Wallace', 'all_star_count': 1},
        {'name': 'Paul Walther', 'all_star_count': 1},
        {'name': 'Ben Warley', 'all_star_count': 1},
        {'name': 'Kermit Washington', 'all_star_count': 1},
        {'name': 'Trooper Washington', 'all_star_count': 1},
        {'name': 'Victor Wembanyama', 'all_star_count': 1},
        {'name': 'Andrew Wiggins', 'all_star_count': 1},
        {'name': 'Jalen Williams', 'all_star_count': 1},
        {'name': 'Jayson Williams', 'all_star_count': 1},
        {'name': 'Mo Williams', 'all_star_count': 1},
        {'name': 'Kevin Willis', 'all_star_count': 1},
        {'name': 'Metta World Peace', 'all_star_count': 1},
        {'name': 'Max Zaslofsky', 'all_star_count': 1},
    ]
    print(f"✅ Created complete list with {len(all_stars)} All-Star players")
    return all_stars

def main():
    print("🎯 SwishAI All-Star Database Builder")
    print("=" * 40)
    create_database()
    all_star_data = create_manual_all_star_list()
    # Assign unique IDs (1-based)
    for idx, player in enumerate(all_star_data, 1):
        player["id"] = idx
    save_players_to_db(all_star_data)
    print(f"\n🎉 Successfully built All-Star database!")
    print(f"📊 Total All-Star players: {len(all_star_data)}")
    print(f"\n🌟 Sample All-Star players:")
    for player in all_star_data[:5]:
        print(f"  {player['name']}: {player['all_star_count']} selections")

if __name__ == "__main__":
    main() 